#!/bin/bash

LOCAL=`pwd`/$1
BRANCH=$2

git clone $LOCAL $BRANCH
pushd $BRANCH

./sync-all -r $LOCAL remote set-url origin
./sync-all --testsuite --nofib get

# add the local repo you are cloning as `working`
./sync-all -r $LOCAL remote add working

ghc-pointremotes

cp mk/build.mk{.sample,}
