#!/bin/bash

UPSTREAM="https://github.com/ghc"
#UPSTREAM="http://git.haskell.org/ghc.git"

WORKING=ghc-working
VALIDATE=ghc-validate
LFORK=ghc-leroux

SRCTREES=.

# Ensure that this doesn't run on accident!
# Requires GHCDIR to exist in the root of your ghc-dev dir.
if [ ! -f GHCDEVDIR ]; then
  echo "GHCDEVDIR does not exist."
  exit 1
fi

pushd $SRCTREES

# Get sources.
git clone $UPSTREAM $WORKING
pushd $WORKING
./sync-all --nofib --testsuite get
popd

ghc-clonetree $WORKING $VALIDATE

popd # pop $SRCTREES.
