#!/bin/bash

UPSTREAM="https://github.com/ghc"
#UPSTREAM="http://git.haskell.org/ghc.git"

SRC="$HOME/ghc/ghc-clone"
WORKING="$HOME/ghc/ghc-working"
FORK="git@github.com:leroux" # remote fork
LFORK="$HOME/ghc/ghc-leroux" # local fork

./sync-all -r $SRC remote add src
./sync-all -r $WORKING remote add working
./sync-all -r $UPSTREAM remote add upstream
./sync-all -r $FORK remote add fork
