#!/bin/bash

GHC="https://github.com/ghc/ghc"

UPSTREAM="https://github.com/ghc"
#UPSTREAM="http://git.haskell.org/ghc.git"

SRC=ghc-clone # isn't to be touched locally... just synced with remotes.
SRCDIR=`pwd`/$SRC
WORKING=ghc-working # work in here
VALIDATE=ghc-validate # pass work to validate before pushing to remotes.

SRCTREES=. # root of all ghc source trees.

# Ensure that this doesn't run on accident!
# Requires GHCDIR to exist in the root of your ghc-dev dir.
if [ ! -f GHCDEVDIR ]; then
  echo "GHCDEVDIR does not exist."
  exit 1
fi

pushd $SRCTREES

# src tree (should never be touched locally)
git clone $GHC $SRC # Get sources.
pushd $SRC
./sync-all --nofib --testsuite --extra get
popd

# working tree
git clone $SRC $WORKING
pushd $WORKING
ghc-pointremotes
./sync-all -r $SRCDIR --testsuite --no-dph get
./sync-all set-url --push fork
popd

# validate tree
git clone $WORKING $VALIDATE
pushd $VALIDATE
ghc-pointremotes
./sync-all -r $SRCDIR --nofib --testsuite get
./sync-all set-url --push fork
popd

popd # pop $SRCTREES.
